/**
 * PolicyAdvisor — Customer-facing chatbot for policy questions
 *
 * EU AI Act classification: LIMITED RISK
 *   - Art. 52: transparency obligation — must identify as AI system
 *   - Art. 13: users must understand what the system can/cannot do
 *
 * SOE constraints:
 *   - Can READ policies and customer safe data
 *   - CANNOT write anything (read-only agent)
 *   - CANNOT access claims (privacy — customer should use claims portal)
 *   - CANNOT access protected characteristics
 *   - CANNOT execute any system commands
 */

import { guardedAction } from '../../soe-client.js';

const AGENT_ID = 'policy-advisor';

export class PolicyAdvisor {
  constructor(store) {
    this.store = store;
  }

  /**
   * Answer a policy question for a customer.
   */
  async answerQuestion(customerId, question) {
    const steps = [];

    // Step 1: Read customer info
    const readCustomer = await guardedAction(
      AGENT_ID, 'Read', { file_path: `data/customers/${customerId}` },
      () => this.store.getCustomerSafe(customerId),
    );
    steps.push(readCustomer);
    if (!readCustomer.executed || !readCustomer.output) {
      return { customerId, status: 'blocked', reason: 'Cannot read customer', steps };
    }

    // Step 2: Read customer's policies
    const customerPolicies = [...this.store.policies.values()]
      .filter(p => p.customerId === customerId);

    const readPolicies = await guardedAction(
      AGENT_ID, 'Read', { file_path: `data/policies?customerId=${customerId}` },
      () => customerPolicies,
    );
    steps.push(readPolicies);
    const policies = readPolicies.executed ? readPolicies.output : [];

    // Step 3: Generate response based on question type
    const response = this._generateResponse(readCustomer.output, policies, question);

    return {
      customerId,
      question,
      status: 'answered',
      response: {
        // EU AI Act Art. 52 — transparency
        aiDisclosure: 'This response was generated by an AI assistant. For complex policy decisions, please contact a human agent.',
        ...response,
      },
      steps,
    };
  }

  /**
   * Attempt to write data — MUST be blocked by SOE.
   * PolicyAdvisor is read-only.
   */
  async attemptWritePolicy(policyId, changes) {
    return guardedAction(
      AGENT_ID, 'Write', { file_path: `data/policies/${policyId}`, content: JSON.stringify(changes) },
      () => ({ error: 'This should never execute' }),
    );
  }

  /**
   * Attempt to read claims — MUST be blocked by SOE.
   * PolicyAdvisor should not access claims data.
   */
  async attemptReadClaims(customerId) {
    return guardedAction(
      AGENT_ID, 'Read', { file_path: `data/claims?customerId=${customerId}` },
      () => this.store.getClaimsForCustomer(customerId),
    );
  }

  /**
   * Attempt to run a system command — MUST be blocked by SOE.
   */
  async attemptBashCommand(command) {
    return guardedAction(
      AGENT_ID, 'Bash', { command },
      () => ({ error: 'This should never execute' }),
    );
  }

  _generateResponse(customer, policies, question) {
    const q = question.toLowerCase();

    if (q.includes('coverage') || q.includes('how much')) {
      return {
        answer: policies.map(p =>
          `Your ${p.type} policy (${p.id}) has coverage of €${p.coverage.toLocaleString()} with a €${p.deductible} deductible.`
        ).join('\n'),
        context: 'coverage-inquiry',
      };
    }

    if (q.includes('premium') || q.includes('cost') || q.includes('price')) {
      return {
        answer: policies.map(p =>
          `Your ${p.type} policy (${p.id}) premium is €${p.premium}/year.`
        ).join('\n'),
        context: 'premium-inquiry',
      };
    }

    if (q.includes('claim') || q.includes('file')) {
      return {
        answer: 'To file a claim, please visit our claims portal or call our claims hotline at +31-800-CLAIMS. Our ClaimsBot will assist with processing.',
        context: 'claims-redirect',
      };
    }

    if (q.includes('renew') || q.includes('expir')) {
      const expiring = policies.filter(p => {
        const end = new Date(p.endDate);
        const threeMonths = new Date();
        threeMonths.setMonth(threeMonths.getMonth() + 3);
        return end <= threeMonths;
      });
      return {
        answer: expiring.length > 0
          ? `The following policies are expiring soon: ${expiring.map(p => `${p.id} (${p.type}, expires ${p.endDate})`).join(', ')}. Contact us to renew.`
          : 'All your policies are current. No renewals needed at this time.',
        context: 'renewal-inquiry',
      };
    }

    return {
      answer: `Hello ${customer.name}, I can help with questions about your ${policies.length} active policy/policies. Ask me about coverage, premiums, renewals, or how to file a claim.`,
      context: 'general',
    };
  }
}
